### ISSUE TITLE
Testing for every module and fix bugs

### ISSUE THREAD

**Issue by SankaD** [SaitoTech/saito-lite-rust#1794]
- [x] SaitoTech/saito-lite-rust#1751
- [x] SaitoTech/saito-lite-rust#1752
- [ ] SaitoTech/saito-lite-rust#1753
- [ ] SaitoTech/saito-lite-rust#1754
- [x] SaitoTech/saito-lite-rust#1755
- [ ] SaitoTech/saito-lite-rust#1756
- [x] SaitoTech/saito-lite-rust#1757
- [ ] SaitoTech/saito-lite-rust#1758
- [ ] SaitoTech/saito-lite-rust#1759
- [x] SaitoTech/saito-lite-rust#1760
- [x] SaitoTech/saito-lite-rust#1761
- [x] SaitoTech/saito-lite-rust#1762
- [ ] SaitoTech/saito-lite-rust#1763
- [ ] SaitoTech/saito-lite-rust#1764
- [x] SaitoTech/saito-lite-rust#1765
- [ ] SaitoTech/saito-lite-rust#1766
- [ ] SaitoTech/saito-lite-rust#1767
- [ ] SaitoTech/saito-lite-rust#1768
- [ ] SaitoTech/saito-lite-rust#1769
- [ ] SaitoTech/saito-lite-rust#1770
- [x] SaitoTech/saito-lite-rust#1771
- [ ] SaitoTech/saito-lite-rust#1772
- [ ] SaitoTech/saito-lite-rust#1773
- [ ] SaitoTech/saito-lite-rust#1750
- [x] SaitoTech/saito-lite-rust#1836
- [ ] #1801
- [ ] #1802
- [ ] #1803
- [ ] #1804
- [ ] #1805
- [ ] #1806
- [ ] #1807
- [ ] #1808
- [ ] #1809
- [ ] #1810
- [ ] #1811
- [ ] #1812
- [x] #1813
- [ ] #1814
- [ ] #1815
- [ ] #1816
- [ ] #1817
- [ ] #1818
- [x] #1819
- [ ] #1820
