### ISSUE TITLE
Refactor Chat Module -- Many concurrent issues

### ISSUE THREAD

**Issue by f8daniel** [SaitoTech/saito-lite-rust#835]
Summary of Major Issues:

- [ ] Chat (saito.io/chat) doesn't render at all [https://github.com/SaitoTech/saito-lite-rust/issues/718] 
- [ ] Private messaging in Arcade crashes [https://github.com/SaitoTech/saito-lite-rust/issues/682]
- [ ] Private messaging in a game module loads Saito Community Chat []
- [ ] Community Chat loads in wrong window [https://github.com/SaitoTech/saito-lite-rust/issues/756]
- [ ] Inconsistent loading of previous messages [https://github.com/SaitoTech/saito-lite-rust/issues/758], [https://github.com/SaitoTech/saito-lite-rust/issues/728]
- [ ] Pictures get sent to wrong chat group [https://github.com/SaitoTech/saito-lite-rust/issues/610]

Summary of Minor Issues:

- [ ] Timestamps inconsistent [https://github.com/SaitoTech/saito-lite-rust/issues/729]
- [ ] User names inconsistent [https://github.com/SaitoTech/saito-lite-rust/issues/704]
- [ ] User icons inconsistent [https://github.com/SaitoTech/saito-lite-rust/issues/584]
(the last two seem to be a consequence of having saito/mixin public keys)

Summary of Trivial Issues:

- [ ] Chat not mobile optimized [https://github.com/SaitoTech/saito-lite-rust/issues/671]
